version: '2.3'
services:
  protonvpn:
    container_name: protonvpn
    image: ghcr.io/tprasadtp/protonwire:latest
    dns: 8.8.8.8
    restart: unless-stopped
    environment:
      IPCHECK_URL: https://checkip.amazonaws.com/
      PROTONVPN_SERVER: ch-my-01.protonvpn.net # Replace with your ProtonVPN server
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY-MBhOcLfWRQeAHr87jXH/zu1Slz3YAVr+ELeQPrEXyko=}
      KILL_SWITCH: "0" # Optional, use with caution
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: bind
        source: C:\Scripting\PRD_SRCIPTS\Wyrd_Scripts\Docker-Dev\DockerCompose\JustProton\conf\private_ky.txt
        target: /etc/protonwire/private-key
        read_only: true
    ports:
      - "8080:80" # Example port, adjust as needed
