version: "3.1"

services:
  postgres:
    container_name: Peppermint-DB
    image: postgres:latest
    restart: always
    volumes:
      - /srv/dev-disk-by-uuid-73dc2c92-3a9f-4f48-a24b-389340b2bd97/home/Appdata/peppermint_db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: p3pp3rmint
      POSTGRES_DB: peppermint

  client:
    container_name: Peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5006:5006
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 5006
      DB_USERNAME: peppermint
      DB_PASSWORD: silica5342
      DB_HOST: postgres
      BASE_URL: http://192.168.8.226:5006