# WORKING ON THIS

################################

version: "2"
services:
  qbittorrentvpn:
    image: chrisjohnson00/qbittorrent-openvpn:latest
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=9qgjWtpMJpffEjWf
      - VPN_PASSWORD=DnKTRrRcXUdQwGisuEBP37FnUNb0keAo
      - PUID=998 #optional
      - PGID=100 #optional
      - WEBUI_PORT_ENV=8080 #optional
      - INCOMING_PORT_ENV=8999 #optional
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.8.0/24
      - NAME_SERVERS=8.8.8.8,192.168.8.2
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - /srv/dev-disk-by-uuid-73dc2c92-3a9f-4f48-a24b-389340b2bd97/config/qbittorrentvpn:/config
      - /srv/dev-disk-by-uuid-73dc2c92-3a9f-4f48-a24b-389340b2bd97/torrents:/downloads
    restart: unless-stopped