version: "2"
services:
  qbittorrentvpn:
    build: .
    image: ubuntu:latest
    container_name: qbittorrentvpn
    privileged: true
    environment:
      - PUID=1000 #optional
      - PGID=100 #optional
      - WEBUI_PORT_ENV=8080 #optional
      - INCOMING_PORT_ENV=8999 #optional
      - LAN_NETWORK=192.168.0.0/24
      - NAME_SERVERS=8.8.8.8,192.168.0.1
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - C:\Scripting\_Assets\Docker\QbittorrentVPN\config:/config
      - C:\Scripting\_Assets\Docker\QbittorrentVPN\downloads:/downloads
    restart: no
