version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    image: ghcr.io/tprasadtp/protonwire:latest
    dns: 8.8.8.8
    restart: unless-stopped
    environment:
      IPCHECK_URL: https://checkip.amazonaws.com/
      PROTONVPN_SERVER: ch-my-01.protonvpn.net # Replace with your ProtonVPN server
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY-MBhOcLfWRQeAHr87jXH/zu1Slz3YAVr+ELeQPrEXyko=}
      KILL_SWITCH: "0" # Optional, use with caution
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: bind
        source: C:\Scripting\PRD_SRCIPTS\Wyrd_Scripts\Docker-Dev\DockerCompose\JustProton\conf\private_ky.txt
        target: /etc/protonwire/private-key
        read_only: true
    ports:
      - "8080:80" # Example port, adjust as needed
    devices:
      - /dev/net/tun:/dev/net/tun
    # Expose pyload container's port here!
    expose:
      - 8080

  qbittorrent:
    depends_on:
      - protonvpn
    container_name: Qbittorrent
    environment:
      TZ: "Australia/Sydney"
      PGID: "1006"
      PUID: "100"
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: unless-stopped
    userns_mode: host
    # The networking of this container is managed by the protonvpn service
    network_mode: service:protonvpn
    volumes:
      # Ensure these paths exist and Docker has access to them
      - C:\Scripting\_Assets\Docker\QbittorrentVPN\config:/config
      - C:\Scripting\_Assets\Docker\QbittorrentVPN\downloads:/downloads

volumes:
  config:


networks:
  internet:
  proxy:
    internal: true
